# Generated by Django 3.1.7 on 2021-03-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0002_promo_normal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
