# Generated by Django 3.1.7 on 2021-04-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0003_auto_20210331_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={'ordering': ['-id']},
        ),
    ]
